In [1]:
import gensim
# Skip gram model 로드
# Load Google's pre-trained Word2Vec model.
model = gensim.models.KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin', binary=True)  

# Word2Vec (Fasttext) 활용해보기  
    -fasttext는 character단위로 여러 조합을 만들어 oov(out of voca)를 보안할 수 있는 특징이 있음.

In [55]:
from gensim.models.fasttext import FastText 

In [333]:
from gensim.test.utils import common_texts  # some example sentences
print(common_texts[:])
print(len(common_texts))
model = FastText(size=4, window=3, min_count=1)  # instantiate
model.build_vocab(sentences=common_texts)
model.train(sentences=common_texts, total_examples=len(common_texts), epochs=1000)  # train

[['human', 'interface', 'computer'], ['survey', 'user', 'computer', 'system', 'response', 'time'], ['eps', 'user', 'interface', 'system'], ['system', 'human', 'system', 'eps'], ['user', 'response', 'time'], ['trees'], ['graph', 'trees'], ['graph', 'minors', 'trees'], ['graph', 'minors', 'survey']]
9


## online learning으로 새로운 단어 벡터 학습하기

In [352]:
print(model)
print(model.wv['system'])
print(model.wv['trees'])
print('systemss' in model.wv.vocab) # Tests if word present in vocab
print('ssystems42342' in model) # Tests if vector present for worda
print(model.wv['ssystemss42342'])
print(model.wv['ssystems'])
print(model.wv['systems'])
print(model.wv['system']+model.wv['ystem']+model.wv['stem']+model.wv['tem'])

FastText(vocab=12, size=4, alpha=0.025)
[ 0.04291693 -0.01690747  0.0535338  -0.01618716]
[ 0.00881604  0.01222524 -0.01944129 -0.00407308]
False
True
[ 0.00900394 -0.04236314  0.04026207 -0.01032737]
[ 0.00900394 -0.04236314  0.04026207 -0.01032737]
[ 0.03528167 -0.02827537  0.06117161 -0.01264922]
[ 0.08470255 -0.18830316  0.14384793 -0.01968226]


C:\Users\admin\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:34: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).


In [130]:
import numpy as np
old_vector = np.copy(model.wv['computation'])
print('computation' in model.wv.vocab)
new_sentences = [
  ['computer', 'aided', 'design'],
     ['computer', 'science'],
     ['computational', 'complexity'],
    ['military', 'supercomputer'],
    ['central', 'processing', 'unit'],
    ['onboard', 'car', 'computer'],
 ]
model.build_vocab(new_sentences, update=True)  # Update the vocabulary
model.train(new_sentences, total_examples=len(new_sentences), epochs=model.epochs)
new_vector = model.wv['computation']

False


In [86]:
print(old_vector)
print(new_vector)

[-0.14463495 -0.08178335  0.01251985 -0.03327958]
[-0.14578187 -0.08251493  0.01255858 -0.03342261]


In [132]:
print('computational' in model.wv.vocab)

True


In [37]:
print(old_vector)
print(new_vector)

[ 0.04378184  0.00647251  0.03973336 -0.01973882]
[ 0.01472269  0.02652524  0.03062194 -0.02947172]
